# -*- mode: python -*-

block_cipher = None

a = Analysis(['bin\\regenerate'],
             pathex=['C:\\cygwin64\\home\\533029\\projects\\regenerate'],
             binaries=None,
             datas=[ ('regenerate\\data\\extra\\template.odt', 'regenerate\\data\\extra'),
                     ('regenerate\\data\\help\\addr_map_help.rst', 'regenerate\\data\\help'),
                     ('regenerate\\data\\help\\bitfield_signal_help.rst', 'regenerate\\data\\help'),
                     ('regenerate\\data\\help\\bitfield_signal_prop_help.rst', 'regenerate\\data\\help'),
                     ('regenerate\\data\\help\\bitfield_value_help.rst', 'regenerate\\data\\help'),
                     ('regenerate\\data\\help\\project_group_help.rst', 'regenerate\\data\\help'),
                     ('regenerate\\data\\help\\regenerate_help.rst', 'regenerate\\data\\help'),
                     ('regenerate\\data\\media\\ModifiedIcon.png', 'regenerate\\data\\media'),
                     ('regenerate\\data\\media\\flop.png', 'regenerate\\data\\media'),
                     ('regenerate\\data\\media\\flop.svg', 'regenerate\\data\\media'),
                     ('regenerate\\data\\ui\\add_export.ui', 'regenerate\\data\\ui'),
                     ('regenerate\\data\\ui\\build.ui', 'regenerate\\data\\ui'),
                     ('regenerate\\data\\ui\\preferences.ui', 'regenerate\\data\\ui'),
                     ('regenerate\\data\\ui\\bitfield.ui', 'regenerate\\data\\ui'),
                     ('regenerate\\data\\ui\\group_text.ui', 'regenerate\\data\\ui'),
                     ('regenerate\\data\\ui\\regenerate.ui', 'regenerate\\data\ui'),
                     ('regenerate\\data\\comment.txt', 'regenerate\\data'),
                     ('regenerate\\data\\verilog.inc', 'regenerate\\data.'),
                     ('regenerate\\writers\\templates\\ipxact.template', 'regenerate\\writers\\templates'),
                     ('regenerate\\writers\\templates\\regblk_mux.template', 'regenerate\\writers\\templates'),
                     ('regenerate\\writers\\templates\\uvm_reg_block.template', 'regenerate\\writers\\templates'),
                     ('regenerate\\writers\\templates\\verilog.template', 'regenerate\\writers\\templates'),
                     ],
             hiddenimports=[
                 "regenerate.writers.asm_equ",
                 "regenerate.writers.c_defines",
                 "regenerate.writers.c_test",
                 "regenerate.writers.decoder",
                 "regenerate.writers.ipxact",
                 "regenerate.writers.reg_pkg",
                 "regenerate.writers.rst_doc",
                 "regenerate.writers.sdc",
                 "regenerate.writers.spyglass",
                 "regenerate.writers.uvm_reg_block",
                 "regenerate.writers.verilog_defs",
                 "regenerate.writers.verilog_param",
                 "regenerate.writers.verliog",
             ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)


exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='regenerate',
          debug=False,
          strip=False,
          upx=True,
          console=True )


coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='regenerate')
